on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun run lint
      - run: bun test
