on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: lint
        run: bun run lint
      - name: test
        run: bun test
